### ISSUE TITLE
Docker pull fails for appendbuilder with virtualenv

### ISSUE THREAD

**Issue by rpasricha** [kubeflow/fairing#101]
If there is a virtualenv in the same directory as my code, it gets packaged and added to the image when using the append builder. However, this image is broken and a `docker pull` will fail with the following error:

```
docker: failed to register layer: Error processing tar file(duplicates of file paths not supported): .
See 'docker run --help'.
```

**Comment by karthikv2k** [comment]
Very good find @rpasricha !

**Comment by r2d4** [comment]
Docker has some restrictions on the rootfs tarball

- no duplicate file paths
- no symlinks (I can't remember if they are just silently ignored or this errors)

Obviously the virtualenv violates both of those.

**Comment by karthikv2k** [comment]
I can see virtualenvs having symlinks. How is the duplicate file paths are result of virtualenv? @rpasricha does your base image also has a virtualenv dir already and the new payload is adding duplicate file paths?

**Comment by r2d4** [comment]
Following symlinks could lead to duplicate paths? I'm not sure - we use the same context generation for the other builders as well. Does it fail on those?

**Comment by rpasricha** [comment]
@karthikv2k I'm just running `examples/simple/main.py` directly, using the base image: `tensorflow/tensorflow:latest-py3`.

@r2d4 I see the same issue when using the docker builder, except here it fails during the build stage (which is a better outcome). Here's the error:

`docker.errors.APIError: 500 Server Error: Internal Server Error ("Error processing tar file(exit status 1): open /app/env2/include/python3.6m/sliceobject.h: no such file or directory")`

**Comment by r2d4** [comment]
We can probably explicitly ignore symlinks in the context tar generation, which should solve our issues

**Comment by karthikv2k** [comment]
@rpasricha can you paste all commands that reproduces this issue? I am interested in knowing how you create virtualenv.

**Comment by rpasricha** [comment]
@karthikv2k Since packaging all of the files takes a while I'm assuming there's a virtualenv in a different directory that has fairing + dependencies installed.

From `examples/simple`
1. `virtualenv -p python3 env`
2. `python main.py`

If using docker builder the image creation will fail, but for append builder you can verify with `docker pull <generated image>`

**Comment by rpasricha** [comment]
@r2d4 I tried ignoring symlinks in the context generation process and that fixed the docker builder error but not append builder.
