### ISSUE TITLE
Implement deployer interface for GCP serving deployer

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/fairing#143]

**Comment by jlewi** [comment]
@karthikv2k How's this coming?What is the GCP deployer? Does this mean deploying on Kubeflow?

**Comment by karthikv2k** [comment]
#189 is ready to merge pending a placeholder for prow presumbmit tests that is causing presumbmit test failures.
This is for deploying on AI Platform prediction. We should change the managed service name from gcp/gcpmanaged to Google AI Platform in the code and docs
