### ISSUE TITLE
Provide customized config options for GCP Deployer

### ISSUE THREAD

**Issue by rpasricha** [kubeflow/fairing#161]
Currently we only allow users to set the region and scale_tier in the GCP deployer. We should allow users to provide more customized deployments.

This can be done by allowing users to provide an arbitrary dictionary for request parameters.

**Comment by jlewi** [comment]
Punting to 0.6 since 0.5 is nearing completion.

What is scale_tier? Does this only matter if not deploying on Kubeflow?
