### ISSUE TITLE
Directly calling predict function in prediction endpoint is failing

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/fairing#179]
```
(train_X, train_y), (test_X, test_y) = read_input('ames_dataset/train.csv')
endpoint.predict(test_X)
```
This fails as it tries to pass a numpy array directly to requests object. @abhi-g and I found it during our manual e2e testing.

**Comment by abhi-g** [comment]
Will this interface allow for batch prediction, i.e., looks like test_X is a collection of data points to make predictions on?

**Comment by karthikv2k** [comment]
it depends on the predict function impl. if the user handles batch of examples then we can do it.
