### ISSUE TITLE
Append builder: Image tag is the same even though base image is different

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#197]
I used the append builder to build an image and then changed the base image and rebuilt.

In both cases the image URI was the same.

```
gcr.io/code-search-demo/fairing-job:BEF9445D
```

Is this expected? I would have expected unique image tags for each build if the base image changed.

**Comment by karthikv2k** [comment]
>Is this expected? I would have expected unique image tags for each build if the base image changed.

The image tag is generated by getting CRC for the preprocessor output https://github.com/kubeflow/fairing/blob/master/fairing/utils.py#L28 that doesn't depend on the base image. 

@r2d4 what is the ideal solution here?

**Comment by r2d4** [comment]
The correct solution is to reference images by their digest

**Comment by jlewi** [comment]
I think this may have been user error on my part. I may not have been sending files to the builder (no output from preprocessor) and that's why the CRC was the same.
