### ISSUE TITLE
Why doesn't PredictionEndpoint/Task interface support the append builder?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#203]
It looks like the PredictionEndpoint interface doesn't support the append builder.

It doesn't look like there's a way to pass to get_builder `needs_deps_installation=False` to force it to use the append builder rather than the ClusterBuilder (Kaniko)

https://github.com/kubeflow/fairing/blob/642530567d0255f88b0f83b0a40b3325c303bfa2/fairing/ml_tasks/tasks.py#L36

/cc @karthikv2k

**Comment by karthikv2k** [comment]
We need to a logic to figure out if requirements.txt or any other deps needs to be installed. We can tackle this in next sprint or so.

**Comment by jlewi** [comment]
@karthikv2k Could you assign a priority to this bug please?

**Comment by jlewi** [comment]
An alternative solution as I did in my demo 
https://github.com/jlewi/kubecon-demo

Is to use the lower level APIs and not use PredictionEndpoint/Task.

@karthikv2k Any thoughts on what a good path forward might be? i.e. should we handle this case by pointing folks to the lower level APIs? Or should we add support to the higher level APIs.

**Comment by karthikv2k** [comment]
We should be able to do this in high level api. We should be able to do it for 0.6.
