### ISSUE TITLE
Don't expose services by default; Don't use Service Type LoadBalancer by default

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#206]
It looks like by default when you deploy with fairing you create a service of type loadbalancer
https://github.com/kubeflow/fairing/blob/642530567d0255f88b0f83b0a40b3325c303bfa2/fairing/deployers/serving/serving.py#L79

This exposes the model on a public endpoint by default.

In general we want to avoid making services publicly available. Especially for fairing since the target audience (datascientists) may not know the security implications of doing so.

By default we should use ClusterIP.

To make the service accessible from outside the cluster we should add an appropriate reverse proxy route (e.g. via Ambassador or ISTIO). This way it will be secured via whatever authentication/authorization method the user has setup.

**Comment by karthikv2k** [comment]
#153

**Comment by r2d4** [comment]
Using a service mesh for routing would preclude fairing from deploying on vanilla Kubernetes clusters then. Is that ok?

**Comment by jlewi** [comment]
@karthikv2k What is the plan for 0.6?

**Comment by karthikv2k** [comment]
We don't have cycles to fix it in 0.6.

**Comment by jinchihe** [comment]
This should be enhanced in #376 , closing the ticket.
