### ISSUE TITLE
Test fairing in an on-prem infrastructure

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/fairing#227]

**Comment by jinchihe** [comment]
I will do some tests for on-prem cluster. Thanks.

**Comment by KikiCS** [comment]
I would like to know how this test goes. I can only find guides that need GCP to work.

**Comment by jinchihe** [comment]
@KikiCS I tested fairing on prem cluster, and added some features and fix bugs for on-prem cluster. For the guide, we are planing for this, and will have doucment for the Fairing APIs.

**Comment by KikiCS** [comment]
Thank you @jinchihe !

**Comment by elviraux** [comment]
closing

**Comment by PoornimaDevii** [comment]
> 
> 
> @KikiCS I tested fairing on prem cluster, and added some features and fix bugs for on-prem cluster. For the guide, we are planing for this, and will have doucment for the Fairing APIs.

@jinchihe While using fairing on on-prem cluster, I was not sure of the fairing backend used and the related build_context_source. Was able to find only context source methods only for clouds but not for on-prem.  Would be good if I know the backend and context source you used while testing on prem.

**Comment by jinchihe** [comment]
@PoornimaDevii You can use the `KubernetesBackend`, or see the example https://github.com/kubeflow/fairing/tree/master/examples/mnist

**Comment by PoornimaDevii** [comment]
> 
> 
> @PoornimaDevii You can use the `KubernetesBackend`, or see the example https://github.com/kubeflow/fairing/tree/master/examples/mnist

@jinchihe Thanks !
