### ISSUE TITLE
Default to current namespace instead of "Kubeflow" or None

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/fairing#233]
Works better in a multi-user setting.
CC @zabbasi

**Comment by jlewi** [comment]
@karthikv2k Any suggestion on how we might tackle this?

Should we do something like

* Have fairing look for POD_NAMESPACE environment variable
* Have JupyterNotebook set POD_NAMESPACE env variable on the pod?

**Comment by jinchihe** [comment]
Has been fixed in https://github.com/kubeflow/fairing/pull/318?
