### ISSUE TITLE
Create a test for distributed training using tf-job deployer

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/fairing#235]

**Comment by jlewi** [comment]
@karthikv2k Any update on this? Is someone working on this? If not should we move back to the backlog from "current sprint".

**Comment by karthikv2k** [comment]
We already have an integration test that uses tf-job . 
https://github.com/kubeflow/fairing/blob/master/tests/integration/gcp/test_running_in_notebooks.py#L40
https://github.com/kubeflow/fairing/blob/master/fairing/frameworks/lightgbm.py#L233

We can add an integration test for tfjob using a tf example later.
