### ISSUE TITLE
xgboost-high-level-apis.ipynb : RuntimeError: Not able to guess the right builder for this job!

### ISSUE THREAD

**Issue by lppier** [kubeflow/fairing#240]
Hi, I trying to run the xgboost-high-level-apis.ipynb example following the instructions here , but am getting the following error.
[RuntimeError: Not able to guess the right builder for this job!](url)
Full error is shown below at the end - Am I doing something wrong here? 

This happens when I run 
```
from fairing import TrainJob
from fairing.backends import KubeflowGKEBackend
train_job = TrainJob(HousingServe, BASE_IMAGE, input_files=['ames_dataset/train.csv', "requirements.txt"],
                     docker_registry=DOCKER_REGISTRY, backend=KubeflowGKEBackend())
train_job.submit()
```
```

Using preprocessor: <class 'fairing.preprocessors.function.FunctionPreProcessor'>
Using docker registry: gcr.io/fairing/fairing-job
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-6b63606d22ca> in <module>()
      2 from fairing.backends import KubeflowGKEBackend
      3 train_job = TrainJob(HousingServe, BASE_IMAGE, input_files=['ames_dataset/train.csv', "requirements.txt"],
----> 4                      docker_registry=DOCKER_REGISTRY, backend=KubeflowGKEBackend())
      5 train_job.submit()

~/anaconda3/lib/python3.6/site-packages/fairing/ml_tasks/tasks.py in __init__(self, entry_point, base_docker_image, docker_registry, input_files, backend)
     47 
     48     def __init__(self, entry_point, base_docker_image, docker_registry, input_files=None, backend=None):
---> 49         super().__init__(entry_point, base_docker_image, docker_registry, input_files, backend)
     50 
     51     def submit(self):

~/anaconda3/lib/python3.6/site-packages/fairing/ml_tasks/tasks.py in __init__(self, entry_point, base_docker_image, docker_registry, input_files, backend)
     36         self.builder = backend.get_builder(preprocessor=preprocessor,
     37                                            base_image=base_docker_image,
---> 38                                            registry=self.docker_registry)
     39         logger.warn("Using builder: {}".format(type(self.builder)))
     40 

~/anaconda3/lib/python3.6/site-packages/fairing/backends/backends.py in get_builder(self, preprocessor, base_image, registry, needs_deps_installation, pod_spec_mutators)
     73                                                    registry,
     74                                                    needs_deps_installation,
---> 75                                                    pod_spec_mutators)
     76 
     77     def get_training_deployer(self):

~/anaconda3/lib/python3.6/site-packages/fairing/backends/backends.py in get_builder(self, preprocessor, base_image, registry, needs_deps_installation, pod_spec_mutators)
     53         else:
     54             # TODO (karthikv2k): Add more info on how to reolve this issue
---> 55             raise RuntimeError("Not able to guess the right builder for this job!")
     56 
     57     def get_training_deployer(self):

RuntimeError: Not able to guess the right builder for this job!
```

**Comment by karthikv2k** [comment]
Hi @lppier ,

Thanks for trying out Fairing. Can you please answer following questions for us to debug your issue?
1. Are you running this in a Jupyter notebook? 
2. Where are you running your Jupyter notebook or python code? your laptop/desktop? in a Kubeflow notebook?
3. Do you have access to the docker daemon? you can test by executing "!docker ps" in your notebook.

We have different means of building docker images and this error occurs if we can't find a right way to build a docker image in your environment.

Thanks
Karthik

**Comment by lppier** [comment]
Hi @karthikv2k ,

> 1. Are you running this in a Jupyter notebook?
Yes.

> 2. Where are you running your Jupyter notebook or python code? your laptop/desktop? in a Kubeflow notebook?
Desktop, with gtx 1080 (if it matters). I followed the instructions here (local) https://www.kubeflow.org/docs/fairing/gcp-local-notebook/

> 3. Do you have access to the docker daemon? you can test by executing "!docker ps" in your notebook.
I usually run docker with sudo, so if I run docker ps it has "permission denied"
I guess this is the issue? I have to run as superuser?

**Comment by karthikv2k** [comment]
One solution is to add your user to the docker group. https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user
You need to logout and login to get change activated.

Do you run Kubeflow on GKE?

**Comment by lppier** [comment]
Yes, I ran it on gke with accordance to the tutorial. I tore down the Kubeflow yesterday for fear of incurring charges - when I get some time I’ll set it up again and report back on this issue - thanks!


________________________________

**Comment by karthikv2k** [comment]
You can try it with GCPManagedBackend quickly if you don't want to worry about tearing down the cluster.

**Comment by lppier** [comment]
Thanks karthikv2k, it works now.
