### ISSUE TITLE
Create API Reference documentation

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/fairing#243]
Options: https://wiki.python.org/moin/DocumentationTools

**Comment by jlewi** [comment]
@karthikv2k Any progress on this? This has been in the "current sprint" for 28days.

**Comment by jlewi** [comment]
@karthikv2k in the current sprint will get doc strings on the code.

That's blocking @joeliedtke from figuring out how to generate reference docs from the docs strings and publish it. Should we split that into a separate issue?

**Comment by joeliedtke** [comment]
I'd like to include this as a part of [Kubeflow/Website 592](https://github.com/kubeflow/website/issues/592).

**Comment by Akashdesarda** [comment]
Will be athere any API refrence like pipeline sdk

**Comment by jinchihe** [comment]
This is already done, See API docs here https://kubeflow-fairing.readthedocs.io/en/latest/index.html

/close
