### ISSUE TITLE
How to add volumes to the serving deployer

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#256]
How can we add volumes to the serving deployer?

The constructor for serving doesn't allow pod_spec_mutators to be set
https://github.com/kubeflow/fairing/blob/master/fairing/deployers/serving/serving.py

Unlike for jobs
But it looks like we can directly set the attribute.

**Comment by jlewi** [comment]
Doesn't look like the pod mutators are applied though.
https://github.com/kubeflow/fairing/blob/08c81437fd9ed720cf4b780e25097fef9fa16cd6/fairing/deployers/serving/serving.py#L35

**Comment by jlewi** [comment]
Actually it looks like deployer.deploy takes a pod spec so we can just modify that.

**Comment by jinchihe** [comment]
Yes, that's my thinking too. Especially for on-prem cluster, we should support preparing(downloading something), training and serving with the persistent volume, all data and model will saved on the volumes, that's more consistent with user behavior than local saved. I'm going to implement, thanks.

/assign @jinchihe 
/cc @karthikv2k
