### ISSUE TITLE
Better error message when tf-job version mismatch happens

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/fairing#277]
/kind feature

**Describe the solution you'd like**
When a user runs an older tf-job operator. The error message thrown by fairing is a standard HTTP 404 message. We should give better instructions for the user to resolve this situation. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jinchihe** [comment]
@karthikv2k do you think if we should expose the tfjob version for user, let user can input that when create deployer? Seems the tfjobs frameworks have no big changes between new and old version.
