### ISSUE TITLE
Dataset Absent in Fairing Job Image

### ISSUE THREAD

**Issue by dpaks** [kubeflow/fairing#283]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Executed the foll. commands 
```
fairing.config.set_builder('docker', registry=DOCKER_REGISTRY, base_image=base_image)
fairing.config.set_deployer('job')
remote_train = fairing.config.fn(HousingServe)
remote_train()
```
remote_train() failed because the fairing_job pod didn't have dataset (ames_dataset) in it.

**What did you expect to happen:**
Training to progress

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I'm trying it on baremetal, not GCP. Image has been built, both base and job image.

**Environment:**

- Fairing version: (use `python -c "import fairing; print(fairing.__version__)"`): 0.5.3
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.5
- Minikube version: NIL
- Kubernetes version: (use `kubectl version`): 1.12.5
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Error thrown when remote_train() was executed**
Push output: Layer already exists None
Push output: Layer already exists None
Push output: Pushed None
Push output: A4E0B25E: digest: sha256:ababc3426003a75bd7d94b921707b93de905d8978abdf37f2c337b0406d81075 size: 3054 None
Push finished: {'Size': 3054, 'Digest': 'sha256:ababc3426003a75bd7d94b921707b93de905d8978abdf37f2c337b0406d81075', 'Tag': 'A4E0B25E'}
Training job fairing-job-ft658 launched.
Waiting for fairing-job-ft658-lrfg9 to start...
Waiting for fairing-job-ft658-lrfg9 to start...
Waiting for fairing-job-ft658-lrfg9 to start...
Pod started running True
error getting status for fairing-job-ft658 (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Length': '331', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 18 Jun 2019 07:18:50 GMT', 'Content-Type': 'application/json'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"fairing-job-ft658-lrfg9\\" is forbidden: User \\"system:serviceaccount:oc:oc\\" cannot get resource \\"pods/log\\" in API group \\"\\" in the namespace \\"oc\\"","reason":"Forbidden","details":{"name":"fairing-job-ft658-lrfg9","kind":"pods"},"code":403}\n'

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-3-9b06dd52af75> in <module>
    112 fairing.config.set_deployer('job')
    113 remote_train = fairing.config.fn(HousingServe)
--> 114 remote_train()

**Logs of fairing-job pod**
Traceback (most recent call last):
  File "/app/function_shim.py", line 49, in <module>
    call(args.serialized_fn_file)
  File "/app/function_shim.py", line 39, in call
    res = obj().train()
  File "<ipython-input-3-9b06dd52af75>", line 81, in train
  File "<ipython-input-3-9b06dd52af75>", line 25, in read_input
  File "/usr/local/lib/python3.5/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.5/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.5/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.5/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.5/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'ames_dataset/train.csv' does not exist: b'ames_dataset/train.csv'

**Comment by shikha130vv** [comment]
can you please share full notebook code that you are executing. Is it same as one of the examples?

**Comment by willturner-gs** [comment]
I'm seeing the same problem. The notebook is: https://github.com/kubeflow/fairing/blob/master/examples/prediction/xgboost-train-and-deploy-in-gcp-from-local-notebook.ipynb

The `ames_dataset/train.csv` file is not available in the training image, so the remote training step fails. It's unclear to me how to provide this file to the training container.

**Comment by fenglixa** [comment]
Reproduced this issue:
```
pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File b'ames_dataset/train.csv' does not exist: b'ames_dataset/train.csv'
> /app/pandas/_libs/parsers.pyx(689)pandas._libs.parsers.TextReader._setup_parser_source()
```
Will provide PR soon.

BR
-Feng

**Comment by fenglixa** [comment]
Reproduced this issue:
```
pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File b'ames_dataset/train.csv' does not exist: b'ames_dataset/train.csv'
> /app/pandas/_libs/parsers.pyx(689)pandas._libs.parsers.TextReader._setup_parser_source()
```
Will provide PR soon.

BR
-Feng

**Comment by chantikummari** [comment]
Facing same issue with the xgboost-high-level-apis.ipynb in azure
