### ISSUE TITLE
core dumped in the training pod based on "tensorflow/tensorflow:1.13.1-py"

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/fairing#286]
/kind bug

**What steps did you take and what happened:**

Run examples under [kubeflow](https://github.com/kubeflow/fairing/tree/master/examples/kubeflow) with `base_image='tensorflow/tensorflow:1.13.1-py3'`

**What did you expect to happen:**
```
[root@jinchi1 ~]# kubectl get pod -n default
NAME                      READY     STATUS    RESTARTS   AGE
fairing-job-qrhqn-9mk8b   0/1       Error     0          2m
fairing-job-qrhqn-f9fqk   0/1       Error     0          2m
fairing-job-qrhqn-s2zsz   0/1       Error     0          1m
fairing-job-qrhqn-t8drr   0/1       Error     0          2m
fairing-job-qrhqn-thzfv   0/1       Error     0          2m
```
Then I checked details by running the command in the container, **core dumped**.
```
root@b85ea2ad3912:/# python /app/function_shim.py --serialized_fn_file /app/pickled_fn.p
Segmentation fault (core dumped)
root@b85ea2ad3912:/# file core.1694
core.1694: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'python /app/function_shim.py --serialized_fn_file /app/pickled_fn.p'
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Fairing version: (use `python -c "import fairing; print(fairing.__version__)"`):
0.5.3
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.5.1
- Minikube version:
- Kubernetes version: (use `kubectl version`): v1.11.1
- OS (e.g. from `/etc/os-release`): redhat 

**NOTE**: If you are using fair from master, please provide us the git commit hash.

**Comment by jinchihe** [comment]
Checked details, guess that's caused by python version? my python is 3.6.5 but in the `tensorflow/tensorflow:1.13.1-py3`, the python version is 3.5.2.

```
root@b85ea2ad3912:/# python --version
Python 3.5.2
```

After I update the base image to `base_image='tensorflow/tensorflow:nightly-py3'` which includes python 3.6.8, the problem cannot be reproduced with the new base image. 

Seem we need to update the base image in the examples? or the problem only happen for on-prem cluster?  Any suggestion? Thanks.

**Comment by karthikv2k** [comment]
#288 #289

**Comment by jinchihe** [comment]
Closed the issue since that will not happen after the PR #291, Thanks.
