### ISSUE TITLE
Fairing training not visible in TFJob Dashboard

### ISSUE THREAD

**Issue by josefkorbel** [kubeflow/fairing#287]
/kind bug

**What steps did you take and what happened:**
I've used the HouseServing notebook example from fairing examples to deploy training job to Kubeflow. I replaced the model with my custom keras model using tf.keras API. I can see the logs how the model is training however I dont see anything in the TFJob Dashboard
[A clear and concise description of what the bug is.]
I am not entirely sure if this is a bug, but should not the training be visible in the TFJob dashboard? The training is running as pod and `kubectl get tfjobs` returns `No resources found.` 

**What did you expect to happen:**
See the training in the TFJob Dashboard

**Environment:**

- Fairing version: 0.5.3
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.5.0
- Kubernetes version: (use `kubectl version`): 1.13.3
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04

**Comment by karthikv2k** [comment]
For single node training we K8s Job API so you won't see that in TfJob dashboard but you can see it in K8s/GKE dashboard.
