### ISSUE TITLE
Check python version during execution for function preprocessor

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/fairing#288]
/kind feature

**Describe the solution you'd like**
Function preprocessor needs the python version to be the same for both local and remote python. If version mismatch, users get not a useful error message, something like unknown opcode. We should check the version mismatch before executing the payload in the function shim and output a useful message.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jinchihe** [comment]
@karthikv2k  Great way to avoid the issue such as core dumped, maybe that's enough to compare main verion and sub version, such as python 2.7, 3.5 or 3.6, do not care 3.6.**x**. And how to pass the local python to remote, is that possaible to touch a tmp file and adding to docker image, and then compare that in remote?

**Comment by karthikv2k** [comment]
just adding [another arg in function shim](https://github.com/kubeflow/fairing/blob/master/fairing/functions/function_shim.py#L47) and [populating it](https://github.com/kubeflow/fairing/blob/master/fairing/preprocessors/function.py#L77) in the function preprocessor should do the job.
