### ISSUE TITLE
Support KFServing to deploy model service

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/fairing#290]
/kind feature

**Describe the solution you'd like**
Suggest Fairing supporting kubeflow [KFServing](https://github.com/kubeflow/kfserving), KFserving has support few usual ML frameworks (such as tensorflow, scikitLearn, pyTorch), and that can be used to deploy a service quickly and easily from trained model and suppport rollout deployments gently. And kubeflow KFServing aims to solve 80% of model serving use cases, so think that's a good choise to deploy ML serving.

@karthikv2k @r2d4 any thoughts for this? Thanks.

**Comment by jinchihe** [comment]
Discussed with @karthikv2k, That's great to support KFServing in the Kubeflow Fairing. I'm going to start doing this. Thanks.

**Comment by karthikv2k** [comment]
Thanks for the initiative @jinchihe 
CC:  @ellis-bigelow @yuzisun
