### ISSUE TITLE
Release v0.6

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/fairing#295]
/kind feature

**Describe the solution you'd like**
Release v0.6 along with KF 0.6

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by vjrantal** [comment]
From my perspective, a release would be a good idea because currently the fairing version in the default notebook images is relatively old so not all the samples work out of box.

**Comment by abhi-g** [comment]
#412 released 0.7.0 of fairing. Along with that we have all the code and tests and test cluster updated.
