### ISSUE TITLE
Adding secrets into the fairing job

### ISSUE THREAD

**Issue by lynochka** [kubeflow/fairing#309]
/kind feature

Could you please tell me what is the easiest way to adding the secrets into the fairing job? 
Are the secrets read from the kubectl backend?

Thank you!

**Comment by jinchihe** [comment]
You may use the `pod_spec_mutators` to add that.

**Comment by shikha130vv** [comment]
@lynochka have you been able to add secrets?

**Comment by jinchihe** [comment]
@shikha130vv What's the user cases? is there a secret that other than GCP and AWS ones?  you need to point the secret name and mounting to pod? right? if use GCP and AWS ones, you can just use `pod_spec_mutators` for this.

```
GCP_CREDS_SECRET_NAME = 'user-gcp-sa'
AWS_CREDS_SECRET_NAME = 'aws-secret'
```

**Comment by dawu76** [comment]
I also had the same question, as I've been unable to run the 'train XGBoost on Kubeflow' cells of multiple example notebooks in this repo. I keep encountering this error:

```
could not check for secret: (403) Reason: Forbidden

HTTP response headers: HTTPHeaderDict({'Audit-Id': 'b6acf46c-b458-4cb6-88f5-dce5a554b8dd', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 04 Sep 2019 22:41:47 GMT', 'Content-Length': '300'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets is forbidden: User \"system:serviceaccount:kubeflow:default-editor\" cannot list resource \"secrets\" in API group \"\" in the namespace \"kubeflow\"","reason":"Forbidden","details":{"kind":"secrets"},"code":403}
```

For example, that's the error I get if I run the following cell in the [examples/prediction/xgboost-gkeop.ipynb](https://github.com/kubeflow/fairing/blob/master/examples/prediction/xgboost-gkeop.ipynb) notebook. Is this notebook supposed to "just work," or do I need to pass in additional arguments somewhere?

```
import fairing

from fairing.builders.cluster import gcs_context
from fairing.builders.cluster.cluster import ClusterBuilder
from fairing.deployers.tfjob.tfjob import TfJob
from fairing.preprocessors.function import FunctionPreProcessor

preprocessor = FunctionPreProcessor(
    function_obj=HousingServe,
    input_files=['ames_dataset/train.csv', "requirements.txt"])

builder = ClusterBuilder(
    registry=DOCKER_REGISTRY, 
    base_image=BASE_IMAGE, 
    preprocessor=preprocessor,
    pod_spec_mutators=[fairing.cloud.gcp.add_gcp_credentials_if_exists],
    context_source=gcs_context.GCSContextSource())

builder.build()
```

Error message

```
Building image using cluster builder.
/opt/conda/lib/python3.6/site-packages/fairing/__init__.py already exists in Fairing context, skipping...
Creating docker context: /tmp/fairing_context_ay2gatdh
/opt/conda/lib/python3.6/site-packages/fairing/__init__.py already exists in Fairing context, skipping...
could not check for secret: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'b6acf46c-b458-4cb6-88f5-dce5a554b8dd', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 04 Sep 2019 22:41:47 GMT', 'Content-Length': '300'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets is forbidden: User \"system:serviceaccount:kubeflow:default-editor\" cannot list resource \"secrets\" in API group \"\" in the namespace \"kubeflow\"","reason":"Forbidden","details":{"kind":"secrets"},"code":403}

---------------------------------------------------------------------------
ApiException                              Traceback (most recent call last)
<ipython-input-9-79188bd00e35> in <module>
     16     context_source=gcs_context.GCSContextSource())
     17 
---> 18 builder.build()
     19 pod_spec = builder.generate_pod_spec()
     20 deployer = TfJob(pod_spec_mutators=[fairing.cloud.gcp.add_gcp_credentials_if_exists],

/opt/conda/lib/python3.6/site-packages/fairing/builders/cluster/cluster.py in build(self)
     83         created_pod = client. \
     84             CoreV1Api(). \
---> 85             create_namespaced_pod(self.namespace, build_pod)
     86         self.manager.log(
     87             name=created_pod.metadata.name,

/opt/conda/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py in create_namespaced_pod(self, namespace, body, **kwargs)
   6113             return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)
   6114         else:
-> 6115             (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)
   6116             return data
   6117 
```

For additional context, I'm running this in a notebook on Kubeflow cluster with these specs -
* kubeflow: version 0.6 - installed on GKE with basic authentication (instead of Cloud IAP), per the [Deploy Kubeflow Using CLI](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/) instructions. I also had to follow the steps listed in [kubeflow/issues/3571](https://github.com/kubeflow/kubeflow/issues/3571) to mount the GCP credentials at /secrets/gcp-service-account-credentials/user-gcp-sa.json and make them visible to my Kubeflow notebooks.
* fairing: version 0.5.3 - I have tried using different versions of fairing installed via pip3 install fairing as well as pip3 install git+git://github.com/kubeflow/fairing.git@master

**Comment by anupash147** [comment]
fairing code assumes docker registry to be in gcp or aws or azure but what is the solution if the registry is a private registry?

**Comment by jinchihe** [comment]
The way to mount the secret by using pod_spec_mutators, take deployer `Job` as example:
```
Job(...,pod_spec_mutators=[get_resource_mutator(volume_type='secret', volume_name='your_secret_name', mount_path='your_mount_path'),...)
```

**Comment by cupdike** [comment]
> get_resource_mutator(volume_type='secret', volume_name='your_secret_name', mount_path='your_mount_path')

Was this supposed to use _volume_mounts_?  That's what the args look like...
`volume_mounts(volume_type='secret', volume_name='your_secret_name', mount_path='your_mount_path')`

**Comment by namlh16** [comment]
> I also had the same question, as I've been unable to run the 'train XGBoost on Kubeflow' cells of multiple example notebooks in this repo. I keep encountering this error:
> 
> ```
> could not check for secret: (403) Reason: Forbidden
> 
> HTTP response headers: HTTPHeaderDict({'Audit-Id': 'b6acf46c-b458-4cb6-88f5-dce5a554b8dd', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 04 Sep 2019 22:41:47 GMT', 'Content-Length': '300'})
> HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets is forbidden: User \"system:serviceaccount:kubeflow:default-editor\" cannot list resource \"secrets\" in API group \"\" in the namespace \"kubeflow\"","reason":"Forbidden","details":{"kind":"secrets"},"code":403}
> ```
> 
> For example, that's the error I get if I run the following cell in the [examples/prediction/xgboost-gkeop.ipynb](https://github.com/kubeflow/fairing/blob/master/examples/prediction/xgboost-gkeop.ipynb) notebook. Is this notebook supposed to "just work," or do I need to pass in additional arguments somewhere?
> 
> ```
> import fairing
> 
> from fairing.builders.cluster import gcs_context
> from fairing.builders.cluster.cluster import ClusterBuilder
> from fairing.deployers.tfjob.tfjob import TfJob
> from fairing.preprocessors.function import FunctionPreProcessor
> 
> preprocessor = FunctionPreProcessor(
>     function_obj=HousingServe,
>     input_files=['ames_dataset/train.csv', "requirements.txt"])
> 
> builder = ClusterBuilder(
>     registry=DOCKER_REGISTRY, 
>     base_image=BASE_IMAGE, 
>     preprocessor=preprocessor,
>     pod_spec_mutators=[fairing.cloud.gcp.add_gcp_credentials_if_exists],
>     context_source=gcs_context.GCSContextSource())
> 
> builder.build()
> ```
> 
> Error message
> 
> ```
> Building image using cluster builder.
> /opt/conda/lib/python3.6/site-packages/fairing/__init__.py already exists in Fairing context, skipping...
> Creating docker context: /tmp/fairing_context_ay2gatdh
> /opt/conda/lib/python3.6/site-packages/fairing/__init__.py already exists in Fairing context, skipping...
> could not check for secret: (403)
> Reason: Forbidden
> HTTP response headers: HTTPHeaderDict({'Audit-Id': 'b6acf46c-b458-4cb6-88f5-dce5a554b8dd', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 04 Sep 2019 22:41:47 GMT', 'Content-Length': '300'})
> HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets is forbidden: User \"system:serviceaccount:kubeflow:default-editor\" cannot list resource \"secrets\" in API group \"\" in the namespace \"kubeflow\"","reason":"Forbidden","details":{"kind":"secrets"},"code":403}
> 
> ---------------------------------------------------------------------------
> ApiException                              Traceback (most recent call last)
> <ipython-input-9-79188bd00e35> in <module>
>      16     context_source=gcs_context.GCSContextSource())
>      17 
> ---> 18 builder.build()
>      19 pod_spec = builder.generate_pod_spec()
>      20 deployer = TfJob(pod_spec_mutators=[fairing.cloud.gcp.add_gcp_credentials_if_exists],
> 
> /opt/conda/lib/python3.6/site-packages/fairing/builders/cluster/cluster.py in build(self)
>      83         created_pod = client. \
>      84             CoreV1Api(). \
> ---> 85             create_namespaced_pod(self.namespace, build_pod)
>      86         self.manager.log(
>      87             name=created_pod.metadata.name,
> 
> /opt/conda/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py in create_namespaced_pod(self, namespace, body, **kwargs)
>    6113             return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)
>    6114         else:
> -> 6115             (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)
>    6116             return data
>    6117 
> ```
> 
> For additional context, I'm running this in a notebook on Kubeflow cluster with these specs -
> 
> * kubeflow: version 0.6 - installed on GKE with basic authentication (instead of Cloud IAP), per the [Deploy Kubeflow Using CLI](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/) instructions. I also had to follow the steps listed in [kubeflow/issues/3571](https://github.com/kubeflow/kubeflow/issues/3571) to mount the GCP credentials at /secrets/gcp-service-account-credentials/user-gcp-sa.json and make them visible to my Kubeflow notebooks.
> * fairing: version 0.5.3 - I have tried using different versions of fairing installed via pip3 install fairing as well as pip3 install git+git://github.com/kubeflow/fairing.git@master

how you solved it ? @dawu76
