### ISSUE TITLE
Code review: possible incorrect condition

### ISSUE THREAD

**Issue by shikha130vv** [kubeflow/fairing#315]
In file fairing.backends.py
In function GKEBackend
if KubeManager().secret_exists(constants.GCP_CREDS_SECRET_NAME, self._namespace):
                msg.append("It seems you don't have permission to list/access secrets in your Kubeflow cluster."
                    "We need this permission in order to build a docker image using Kubeflow cluster."
                    "Adding Kubeneters Admin role to the service account you are using might solve this issue.")

master branch after 123 commits

**Comment by jlewi** [comment]
@shikha130vv Can you please explain what the incorrect condition is?

**Comment by shikhabitgrit** [comment]
What I cannot understand is that if the function secret_exists returns true, which will happen if secret exists and is accessed, the message conveys that user may not have access to secrets....

**Comment by xauthulei** [comment]
@shikha130vv , I have removed that conveys messages. Thanks.

**Comment by jinchihe** [comment]
@shikha130vv The issue should be addressed already, would you mind close this? thanks.
