### ISSUE TITLE
Add document for Fairing APIs

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/fairing#326]
/kind feature

**Describe the solution you'd like**
Kubeflow Fairing should have baisc documents for Fairing APIs, so that the user can just reading the documents when calling APIs, instead of reading code.

**Anything else you would like to add:**

**Comment by jinchihe** [comment]
I prefer to use the `sphinx` to generate the docs for Fairing APIs. I would like have a demo for the Fairing community to show my thoughts by the PR #338. Thanks.

**Comment by swiftdiaries** [comment]
We can use this to track the docs
/assign @brightfly 
/assign @hamedhsn 
/assign @jinchihe 
/assign@swiftdiaries 
/cc @karthikv2k

**Comment by jinchihe** [comment]
To be avoid duplicating efforts, with all due respect, I suggest the assignment can be as following to finish the docStrings for functions/class. You can tell me or append to change if you are interested in other. 

1. Owner: @brightfly
backends/
builders/
cloud/

2. Owner: @hamedhsn
config.py/
deployers/
frameworks/

3. Owner: @jinchihe 
functions/
http_utils.py
kubernetes/
utils.py

4. Owner: @swiftdiaries 
ml_tasks
notebook
preprocessors
runtime_config.py [Seems no need]

Generate docs using the `sphinx` and update #338 if needed after finished docstrings. Owner: @jinchihe 

Reviewer for the docstring changes: @karthikv2k @abhi-g 

Target date:
1. Finishing draft (send PR for reviewing): Aug 16
2. Megering PR(updated to address reviewing comments): Aug 23
3. Generating final Fairing API docs: Aug 30

Comments?  Thank you very much for the cooperation.

**Comment by hamelsmu** [comment]
Hello @jinchihe did you mean to tag me above ?  Maybe you accidentally tagged the wrong person?  LGTM except the dates I likely need an additional week

**Comment by jinchihe** [comment]
> Hello @jinchihe did you mean to tag me above ? Maybe you accidentally tagged the wrong person? LGTM except the dates I likely need an additional week

@hamelsmu Updated. Thanks for the reminder. Sure, that's depends on your working, just proposal date, not deadline :-)

**Comment by jinchihe** [comment]
Hello @hamedhsn @swiftdiaries @@brightfly,
I recommend you use the [pyment](https://github.com/dadadel/pyment) to generate the DocString format and then just need to add description for function and agrs. I did like this in the PR #352 for my owned parts. Thanks.

**Comment by hamelsmu** [comment]
@jinchihe I really apologize but I have to drop out of this effort temporarily.  I was supposed to be using fairing at work so this was a natural way for me to document the library while using it, but unfortunately, I have been assigned to something different.  However, I do plan on coming back and contributing hopefully in the near future.  Sorry about this 🙇

**Comment by jinchihe** [comment]
@hamelsmu No problem. Plan couldn't catch up with change sometimes, haha. I will try to take your parts once get chance. Thanks.

**Comment by hamedhsn** [comment]
@jinchihe I ll take care of those part, as you tagged me originally ;)

**Comment by jinchihe** [comment]
> @jinchihe I ll take care of those part, as you tagged me originally ;)

@hamedhsn Wow, Exciting! Welcome. Great thanks for your contribution in advance. :-)

**Comment by hamedhsn** [comment]
> > @jinchihe I ll take care of those part, as you tagged me originally ;)
> 
> @hamedhsn Wow, Exciting! Welcome. Great thanks for your contribution in advance. :-)

No problem. PR: https://github.com/kubeflow/fairing/pull/354

**Comment by jinchihe** [comment]
@xauthulei @QxiaoQ  @zoyun @wzhanw

Thanks for your docString contribution in advance!
 
1. Please install [pyment](https://github.com/dadadel/pyment) and then use the tool to generate the docstring framework for your parts, 
2. And then add docStrings for each function and class manually, please see the PR https://github.com/kubeflow/fairing/pull/346 for examples.

To be avoid duplicating efforts, with all due respect, I suggest the assignment for left parts can be as following to finish the docStrings for functions/class. You can tell me or append to change if you are interested in other.

  Owner: @wzhanw
    kubeflow/fairing/builders/

  Owner: @zoyun
    kubeflow/fairing/cloud/
    kubeflow/fairing/backends/

  Owner @xauthulei @QxiaoQ
    kubeflow/fairing/ml_tasks/
    kubeflow/fairing/notebook/
    kubeflow/fairing/preprocessors/
    kubeflow/fairing/runtime_config.py (Seems no need?)

**Comment by xauthulei** [comment]
@jinchihe , I will take action later, Thanks

**Comment by zoyun** [comment]
@jinchihe Me too.

**Comment by xauthulei** [comment]
My parts are done:

> kubeflow/fairing/runtime_config.py (Seems no need?)

This python file is too simple without complex logic, we could ignore that.  

>kubeflow/fairing/preprocessors/

For this part, I have committed the PR and associated with this issue, you could review them when you are free. Thanks.

**Comment by xauthulei** [comment]
@jinchihe

**Comment by jinchihe** [comment]
@xauthulei Really great! Thanks!

**Comment by jinchihe** [comment]
@wzhanw Any plan to finish this?  thanks a lot!

**Comment by xauthulei** [comment]
For this changes, we need to enable the `pylint`  when using the **VScode** to edit. so that we could avoid the`kubeflow-fairing-presubmit ` job failed.
