### ISSUE TITLE
The pod_spec_mutators is inflexible

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/fairing#328]
/kind feature

**Describe the solution you'd like**
The `pod_spec_mutators` is inflexible, for example:
1. The `pod_spec_mutators` supports the built-in functions but I think we should let user can define the function then speficy the function by using `pod_spec_mutators`.
2. The `pod_spec_mutators` does not support pass parameter, for example, if user want to add a secret using `pod_spec_mutators`, need to pass the secret name, but seem the current implement cannot get that.

Personally I suggest to enhance the pod_spec_mutators mechanism to let it more flexible.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jinchihe** [comment]
@karthikv2k @abhi-g Any comments for this?

**Comment by karthikv2k** [comment]
> 1. The `pod_spec_mutators` supports the built-in functions but I think we should let user can define the function then speficy the function by using `pod_spec_mutators`.
You can add additional parameter to backend constructor to accept user provided pod spec mutators.

> 2. The `pod_spec_mutators` does not support pass parameter, for example, if user want to add a secret using `pod_spec_mutators`, need to pass the secret name, but seem the current implement cannot get that.
You achieve this without modifying current design. Checkout https://github.com/kubeflow/fairing/blob/master/fairing/kubernetes/utils.py#L3

**Comment by jinchihe** [comment]
@karthikv2k  Many thanks for pointing out! The `k8s_utils.get_resource_mutator`  idea is really great! I will update that following the function done once get change.
