### ISSUE TITLE
RuntimeError: The Python version  mismatches 

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/fairing#340]
/kind bug

**What steps did you take and what happened:**
```
DOCKERHUB_USERNAME = 'seedjeffwan'
DOCKER_REGISTRY = '{}'.format(DOCKERHUB_USERNAME)
fairing.config.set_builder('append',base_image='tensorflow/tensorflow:1.13.1-py3', registry=DOCKER_REGISTRY, push=True)
fairing.config.set_deployer('job')

def train():
    hostname = tf.constant(os.environ['HOSTNAME'])
    sess = tf.Session()
    print('Hostname: ', sess.run(hostname).decode('utf-8'))

if __name__ == '__main__':
    remote_train = fairing.config.fn(train)
    remote_train()

```

and see error message 
```
Finished upload of: seedjeffwan/fairing-job:CBF947AD
Pushed image seedjeffwan/fairing-job:CBF947AD in 113.38928063900005s.
The job fairing-job-sltq2 launched.
Waiting for fairing-job-sltq2-h4jzb to start...
Waiting for fairing-job-sltq2-h4jzb to start...
Waiting for fairing-job-sltq2-h4jzb to start...
Failed to launch fairing-job-sltq2-h4jzb, reason: Error, message: None
Cleaning up job fairing-job-sltq2...
Traceback (most recent call last):
  File "/app/function_shim.py", line 59, in <module>
    compare_version(args.python_version)
  File "/app/function_shim.py", line 38, in compare_version
    + local_python_version + ' in the local environment.')
RuntimeError: The Python version 3.5.2 mismatches with Python 3.7.3 in the local environment.

```

I create a notebook locally by running `jupyter notebook` and my machine python version is 3.7.3. When it schedule job on kubernetes, it encounter this problem. 
```
!python3 -V
Python 3.7.3
```

I enter `tensorflow/tensorflow:1.13.1-py3`  and notice python3 version is `3.5.2`. That's probably the reason.  I understand it's good to check version for potential compatibility issues. 
By looking at the code, I think it doesn't make sense to compare full version. To make sure compatibility, I think major (3) version or minor (5,6,7) are necessary, patch version is not helpful here. (See my comments below)

https://github.com/kubeflow/fairing/blob/8a350ea2c453e2e06f2b7e534de88a2936f9711a/fairing/functions/function_shim.py#L34-L38

**What did you expect to happen:**
In this example, The behavior is definitely correct but we need improvement to only compare to minor version

**Environment:**
- Fairing version: (use `python -c "import fairing; print(fairing.__version__)"`): 0.5.3
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.6.0
- Minikube version: 
- Kubernetes version: (use `kubectl version`): 1.13
- OS (e.g. from `/etc/os-release`):

**NOTE**: If you are using fair from master, please provide us the git commit hash.

**Comment by Jeffwan** [comment]
I can help on the patch if you think it's reasonable.  Based on the python compatible documentation.

### Compatibility Levels
- Compatible: Python version x.y is compatible with w.z if x == w and y >= z
- Potentially compatible: Python version x.y is potentially compatible to version w.z if x == w and y < z
- Incompatible: Python version x.y is incompatible with version w.z if x != w

1. We only compare major and minor version. Micro version should be ignored. 
2. local development python minor version can be lower or equal to remote python minor version is major version is same.

**Comment by jinchihe** [comment]
@Jeffwan That works as design. Pls see discussion in the https://github.com/kubeflow/fairing/issues/288 and https://github.com/kubeflow/fairing/pull/291. Thanks.

**Comment by Jeffwan** [comment]
Hi Jinchi, sorry for taking long to come back. 
I am still a little bit confused, checking design, description in the issue and pr, seems we want to compare major and minor? But in the code implementation, it does compare full version.

In your PR, "In the patch we just compare the Python major and minor version, and igore micro version, for examples, 3.6.5 will mismatch with 3.5.2, but match with 3.6.8."
and in your method annotation, https://github.com/kubeflow/fairing/blob/c5be73f0f6304a37ebea21f9aa1d97156a9e4e8e/kubeflow/fairing/functions/function_shim.py#L41

I made some changes, could you help take a look?
#377

**Comment by jinchihe** [comment]
@Jeffwan In my initial thought, we should just compare major and minor verions. but the PR #291 is updated as @karthikv2k comments that we should also conver micro version, you can read details by going though the #291 .

Not sure has problem if the micro version mismatch, yes, we can reconsider that.
