### ISSUE TITLE
cluster builder should use a job not a pod

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#349]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Cluster builder is currently creating a pod
https://github.com/kubeflow/fairing/blob/be8d42957077cb9844fcaed0f8cada8c74a982fc/fairing/builders/cluster/cluster.py#L72

I think it would be better to create a K8s Job. 

i also don't think we need to explicitly delete the job after its done. We can rely on the K8s TTL that's being added for jobs.

Having the job spec is useful for debugging.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jinchihe** [comment]
/assign 
Will address that later. Thanks.

**Comment by nrchakradhar** [comment]
@jinchihe Can I try to make the changes for this. This will be my first PR though so might take some time. Would that be fine?

**Comment by jinchihe** [comment]
@nrchakradhar Sure. Thanks for picking up. I'm waiting for review your changes.

/assign @nrchakradhar
