### ISSUE TITLE
Release kubeflow-fairing package

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/fairing#370]
/kind feature

**Describe the solution you'd like**
Since the pacakge name has been rename to kubeflow-fairing in the PR #359, use can install the pacakge 0.0.1 by 
```
pip install kubeflow-fairing
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jinchihe** [comment]
@jlewi @abhi-g what do you think about the `kubeflow-fairing` package version? since the `fairing` 0.5.3 has been released in Pypi, is that release as  `kubeflow-fairing 0.6` or  `kubeflow-fairing 0.1`? Thanks.

**Comment by jlewi** [comment]
I would vote to go with 0.6 or 0.7; i.e. not reset the version back to 0.1 just because the package name changed.

I would also try to keep the version numbers in sync with kubeflow as long as we can. If that means we skip a major release (e.g. there is no 0.6) I think that's ok.

**Comment by jinchihe** [comment]
@jlewi OK, I'm going to release `kubeflow-fairing 0.6` version, and relase 0.6.x for P1 or S1 issues. And will release 0.7 version with kubeflow 0.7 in sync. Thanks.

/assign @jinchihe 
/cc @abhi-g

**Comment by jinchihe** [comment]
Hello @jlewi @abhi-g,

Kubeflow-fairing 0.6.0 has been released: https://pypi.org/project/kubeflow-fairing/
```
(python36) [root@jinchi1 ~]# pip install kubeflow-fairing
Collecting kubeflow-fairing
  Downloading https://files.pythonhosted.org/packages/d3/b2/348b73a2705f2bb789976feeba6aa086dbc6546c5c27019b15fc89498f41/kubeflow_fairing-0.6.0-py3-none-any.whl (144kB)
     |████████████████████████████████| 153kB 256kB/s
Requirement already satisfied: google-cloud-storage>=1.13.2 in /opt/kubeflow/python3/python36/lib/python3.6/site-packages (from kubeflow-fairing) (1.16.1)

......

Requirement already satisfied: wcwidth in /opt/kubeflow/python3/python36/lib/python3.6/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->notebook>=5.6.0->kubeflow-fairing) (0.1.7)
Installing collected packages: kubeflow-fairing
Successfully installed kubeflow-fairing-0.6.0
(python36) [root@jinchi1 ~]#
(python36) [root@jinchi1 ~]# pip3 show kubeflow-fairing
Name: kubeflow-fairing
Version: 0.6.0
Summary: Kubeflow Fairing Python SDK.
Home-page: https://github.com/kubeflow/fairing
Author: Kubeflow Authors
Author-email: hejinchi@cn.ibm.com
License: Apache License Version 2.0
Location: /opt/kubeflow/python3/python36/lib/python3.6/site-packages
Requires: azure, google-auth, cloudpickle, kubernetes, httplib2, numpy, future, google-api-python-client, oauth2client, boto3, setuptools, urllib3, google-cloud-storage, docker, six, tornado, requests, notebook
Required-by:
(python36) [root@jinchi1 ~]#
```

**Comment by abhi-g** [comment]
Thanks @jinchi

**Comment by yantriks-edi-bice** [comment]
The Fairing documentation in Kubeflow states that "Kubeflow notebook servers that are built from one of the standard Jupyter Docker images include Kubeflow Fairing and come preconfigured for using Kubeflow Fairing to run training jobs on your Kubeflow cluster." It seems however that it does so with an older version of Fairing, 0.5, and none of the examples work, modules have been renamed etc.

**Comment by abhi-g** [comment]
fair point Yannis. @jinchi should we update the dockerfile for Jupiter
Notebooks to install the latest release of fairing. The examples do work
with it.

**Comment by jinchihe** [comment]
I saw there is a PR to upgrade Fairing in Notebook image. https://github.com/kubeflow/kubeflow/pull/4645 thanks
