### ISSUE TITLE
fairing should support deploying models

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#38]
We'd like to support deploying models using fairing.

A strawman goal would be able to walk through mnist E2E entirely in a notebook.

e.g. train the model, deploy the model, send predictions to the model.

**Comment by jlewi** [comment]
I think there are potentially two different cases we should consider.

1. A TensorFlow model that is exported as SavedModel proto
1. A non-TF model

In the first case if the training function exports a saved model we can just deploy a TFServing instance that loads that model.

In the second case, I think the user would need to define a predict method that would then be invoked by RPC. We might want to use Seldon in this case.

Another problem we'll need to figure out is how to pass the model from training to serving.

**Comment by jlewi** [comment]
Should we split this into separate issue for TF and non-TF models?

**Comment by karthikv2k** [comment]
> I think there are potentially two different cases we should consider.
> 
> 1. A TensorFlow model that is exported as SavedModel proto
This is tracked in #44 
> 2. A non-TF model
This is completed.
