### ISSUE TITLE
Example notebook not working on local cluster

### ISSUE THREAD

**Issue by benoitdr** [kubeflow/fairing#381]
/kind bug

**What steps did you take and what happened:**
Installing and configuring kubeflow and kubeflow fairing according to procedure on kubeflow website, using ubuntu 18.04 and microk8s/

Running fairing/examples/notebook/fairing-xgboost.ipynb on local kubeflow 0.6.2 cluster

First, "from kubeflow import fairing" returns "ModuleNotFoundError: No module named 'kubeflow'"
Replacing by "import fairing"

Then I'm getting
Compute Engine Metadata server unavailable onattempt 1 of 3
Compute Engine Metadata server unavailable onattempt 2 of 3
Compute Engine Metadata server unavailable onattempt 3 of 3
...

DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

It seems fairing is trying to connect to GCP while I want a local solution.

**What did you expect to happen:**
Notebook should run without issue, also on local clusters, not only on GCP

**Anything else you would like to add:**
The documentation is not correct, at least for non GCP deployements :
> The standard Kubeflow notebook images include Kubeflow Fairing and come preconfigured to run training jobs on your Kubeflow cluster. No additional configuration is required.

**Environment:**

- Fairing version: (use `python -c "import kubeflow.fairing; print(kubeflow.fairing.__version__)"`): 0.5 (embedded in image gcr.io/kubeflow-images-public/tensorflow-1.13.1-notebook-cpu:v0.5.0 proposed by kubeflow 0.6.2)
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.6.2
- Minikube version: Microk8s 1.15.3
- Kubernetes version: (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.3 LTS

**Comment by jinchihe** [comment]
@benoitdr The fairing is renamed recently to kubeflow-fairng, please install the kubeflow-fairing using pip, and try again. Seems the fairing in the image is not updated, the new image should include kubeflow-fairing.

For 2nd problem, seems you need to configure the Docker regestry to avoid that if you do not want to run on GCP.

**Comment by benoitdr** [comment]
@jinchihe thanks for your help. Unfortunately I cannot configure docker registry within the notebook container. I think it's a privilege problem. See my comment in https://github.com/kubeflow/fairing/issues/248#issuecomment-534477959

**Comment by benoitdr** [comment]
Indeed uninstalling fairing and installing kubeflow-fairing (using pip) inside the notebook container solved the first issue. The images should be updated otherwise the hard statement in the doc is not valid 

> "The standard Kubeflow notebook images include Kubeflow Fairing and come preconfigured to run training jobs on your Kubeflow cluster. No additional configuration is required."

Still I cannot authenticate ('docker login') from the notebook, since sudo is not granted in the image proposed by kubeflow.
I would need to pass GRANT_SUDO=yes argument to the container but I don't see how to do that with kubeflow (there is a "Configurations" drop-down in the notebook server spawner but it is empty and unusable)

**Comment by joeliedtke** [comment]
/close

I think that this issue was resolved in kubeflow/kubeflow#4645.
