### ISSUE TITLE
ClusterBuilder: use account default-editor when available

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/fairing#403]
/kind feature

**Describe the solution you'd like**
[ClusterBuilder](https://github.com/kubeflow/fairing/blob/51e56fb135b6d8c9ad4c5e48637bfbcabb2ae173/kubeflow/fairing/builders/cluster/cluster.py) should use service account `default-editor` when available.
Starting v0.7 default GCP auth method will be workload identity through `default-editor`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jlewi** [comment]
@abhi-g or @jinchihe could one of you take a look at this?

**Comment by kunmingg** [comment]
Seems fixed on master head: https://github.com/kubeflow/fairing/pull/395

**Comment by kunmingg** [comment]
Updated fairing version here: https://github.com/kubeflow/examples/pull/662
