### ISSUE TITLE
ClusterBuilder doesn't allow setting custom Dockerfile - Needed for xgboost_synthetic

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#404]
/kind bug

**What steps did you take and what happened:**
ClusterBuilder doesn't allow setting a docker file. Instead it always writes a given template.

https://github.com/kubeflow/fairing/blob/58c67efacc5bacbbdad3f91607cccfce4a563fd9/kubeflow/fairing/builders/cluster/cluster.py#L47

https://github.com/kubeflow/fairing/blob/7c93e888c3fc98bdf5fb0140e90f6407ce7a807b/kubeflow/fairing/builders/dockerfile.py#L9

We need this for xgboost_synthetic with 0.7.

With 0.7 our jupyter images are now built from the TF images. By default the user is set to jovyan and the user doesn't have permission to install the python packages globally.

So we need to use a custom Dockerfile that sets the user to root does the pip install and then sets it back to jovyan.

Related to kubeflow/examples#655

**Comment by jlewi** [comment]
I think we can work around this by using an older docker image for the base image in xgboost_synthetic. So I don't think we need to block 0.7.0.

But we should try to update it soon.

@jinchihe  any chance you could pick this up? I think its an easy fix. I think we just need to skip writing the dockerfile if one is supplied to the clusterbuilder.

**Comment by jinchihe** [comment]
@jlewi Got that.
/assign
