### ISSUE TITLE
Run notebook locally launch on K8s cluster

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#41]
I think one of the biggest use cases for fairing will be running a notebook locally but firing off jobs on a cluster.

Does this already work? I assume its just a matter of configuring fairing to communicate properly with the K8s cluster. 

Lets assume the user isn't running in a container; i.e. they just ran jupyter on their local machine. Can we get the K8s config from their kubeconfig file?

We can close this issue once we have instructions for how to make this work.

**Comment by swiftdiaries** [comment]
I'd like to try this out :) 
/assign @swiftdiaries

**Comment by wbuchwalter** [comment]
Yes, this already works.
Fairing will check if it's running in k8s or not and use local or in-cluster config consequently.
So as long as you have access to the kubeconfig it will work. 
The append builder is probably what you want to use, that way you don't have any dependency on docker.

**Comment by jlewi** [comment]
@swiftdiaries Any progress on this?

I'm downgrading to P2 for lack of resources and because its not part of the critical CUJs for 0.5.

**Comment by r2d4** [comment]
This should already work. Please reopen if you're having difficulty still.

/close
