### ISSUE TITLE
Hosting kubeflow-fairing document in the readthedocs

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/fairing#413]
/kind feature

**Describe the solution you'd like**
Hosting kubeflow-fairing document in the https://readthedocs.org, just like kubeflow pipeline done https://kubeflow-pipelines.readthedocs.io/en/latest/index.html

**Comment by sarahmaddox** [comment]
Pipelines has hosted the Python SDK docs on Read the Docs. The API reference for Pipelines is on kubeflow.org.

You should create a new Reference section in the Fairing section of the docs:
https://www.kubeflow.org/docs/fairing/reference/

To do that, follow the pattern of the "Reference" section in the Pipelines section of the docs:
https://www.kubeflow.org/docs/pipelines/reference/

In the new section, add the API reference docs as HTML - see the Pipelines page as an example.
Also add a link to the SDK docs on readthedocs.

When ready, please send your PR to @joeliedtke for review. He can help you with getting the doc metadata and structure correct.

**Comment by jinchihe** [comment]
OK, Thanks @sarahmaddox @joeliedtke
