### ISSUE TITLE
Update kaniko image 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#426]
/kind feature

The kaniko image is quite old
https://github.com/kubeflow/fairing/blob/master/kubeflow/fairing/constants/constants.py#L58

Its currently 0.7.0 but it looks like Kaniko is now on 0.14.0

I ran into issues with 0.7.0 when trying to run the USER command in Dockerfiles with 0.7.0. Updating to 0.14.0 fixed this.

This appears to be a known issue in earlier versions of Kaniko
 https://github.com/GoogleContainerTools/kaniko/issues/477

**Comment by jinchihe** [comment]
/assign @fenglixa

Could you please help to apply the patch for this? Thanks.
