### ISSUE TITLE
Figure out how to monitor TFJobs launched by fairing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#43]
We need to figure out how we want to monitor TFjobs launched from a notebook using fairing.

Right now we just tail the logs of the pods. Does this prevent execution of other cells in the notebook?

Should we just provide a link to dashboards? Should these links be configurable based on the user's deployment? e.g. on GKE we would provide links to stackdriver and the GKE workloads dashboard?

Should we use the TFJobs dashboard?

**Comment by r2d4** [comment]
I think tailing the logs is sufficient. We can provide a way to retrieve logs for completed jobs or save logs to object storage if users request it. I think we can close this and open up separate issues with more concrete feature requests if needed? @jlewi
