### ISSUE TITLE
Release Kubeflow-Fairing 0.7.1

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/fairing#440]
/kind feature

**Describe the solution you'd like**
Release Kubeflow-Fairing 0.7.1

since there some new features such as supporting deploy PyTorchJob and new way TFJob deployment, etc.. I would like to release new `kubeflow-fairing` 0.7.1 pacakge to Pypi with kubeflow 0.7.1 release.

@abhi-g Do you think if any more feature or bugs need to be fixed before `kubeflow-fairing` 0.7.1? Thanks.

/assign @jinchihe

**Comment by abhi-g** [comment]
@jinchihe I think we are good to go.
The only reason I asked to make this into a separate PR was to ensure feature changes could be merged / rollbacked etc. without worrying about the ordering of their PRs etc.

**Comment by jinchihe** [comment]
> The only reason I asked to make this into a separate PR was to ensure feature changes could be merged / rollbacked etc. without worrying about the ordering of their PRs etc.

@abhi-g Yes, I understood your comments. I will send a separate PR to update version and then release new one.
