### ISSUE TITLE
Create a python method to bulk apply YAML specs for KF resources

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#453]
/kind feature

See the function `apply_k8s_specs`
https://github.com/kubeflow/examples/blob/21b24b2bf083b832d6589625d002e0865a62b183/mnist/k8s_util.py#L32

This is function is really useful in notebooks we are using as KF tutorials. In the notebook we can basically just define a list of strings containing YAML specs and then apply them. (See how its used in the mnist example in that PR).

I think it would make since to create a function like that in the fairing SDK. I didn't do that originally for reasons of expediency.

This would make it easier to use notebooks to create self paced tutorials that highlight what the K8s resources look like to help users understand how to use them.

**Comment by jinchihe** [comment]
/assign 

Will investigate and implement this. Thanks.
