### ISSUE TITLE
InCluster Builder - Context Source for vanilla-k8s

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/fairing#456]
/kind feature

**Describe the solution you'd like**
Currently, there are two docker context sources for kaniko used for the in-cluster builder.
1. GCS
2. S3

For vanilla-k8s, it'd be good to add two options:
1. MinioContextSource
2. VolumeContextSource

**Anything else you would like to add:**
This is currently a blocker for https://github.com/kubeflow/examples/issues/725

/cc @johnugeorge @jlewi

**Comment by jlewi** [comment]
@swiftdiaries could you use the S3 context source with MinIO?

**Comment by swiftdiaries** [comment]
I tried using it initially. The context prepare function authenticates to AWS via a 'sts' resource in the boto3 client. Minio needs authentication via the 's3' resource in the same. 
And it looks like kaniko needs a specific set of env vars on the podspec to use the MinIO context. 
Kaniko Reference here: https://github.com/GoogleContainerTools/kaniko/pull/698#issue-287745962
