### ISSUE TITLE
Set output_map on TrainJob

### ISSUE THREAD

**Issue by colinfindlay-nz** [kubeflow/fairing#459]
/kind feature

I'm new Kubeflow and fairing - but I can't seem to set up the scenario I'm after. Everything I've done so far is from my local machine, not a Notebook.

I was using the `TrainJob` with the `KubeflowGKEBackend`. It was working well, but for some reason you can't set `output_map` - it's simply not a paramter and is forced to `{}`

Alternatively I have tried `fairing.config.set_(preprocessor|builder|deployer)` - which lets me set up the structure I need perfectly - but I can't work out how to configure it to use KubeflowGKEBackend.

I'm also not sure which of these 2 methods is the preferred option, the documentation isn't super clear on one vs the other, and the examples seem to use both.

So - I guess the feature request is for `output_map` on TrainJob constructor - or better documentation ;-)

**Comment by jinchihe** [comment]
Personally I suggest you use low level APIs such as `preprocessor|builder|deployer`, but yeah, we can enhance here to let user set `output_map `.
