### ISSUE TITLE
support local prediction with python models (scikits/xgboost)

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#46]
We need to support running prediction inside the notebook for python models (e.g. scikits/xgboost).

What should the input output format be? 

Should we use numpy arrays?
Should we follow Seldon's API?

/cc @cliveseldon

**Comment by r2d4** [comment]
/assign @r2d4
for documenting/exploring xgboost example.

**Comment by jlewi** [comment]
@r2d4 @karthikv2k How's this coming? What work is remaining after #91?

**Comment by karthikv2k** [comment]
Needs #95 [WIP] to support deploying models from Notebook.
