### ISSUE TITLE
fairing 2020 ROADMAP 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#468]
/kind feature

The roadmap for fairing is probably in need of a refresh. What are the high level goals for 2020?

@jinchihe @animeshsingh any interest in driving this? I think it would be great to put together some ideas and discuss it at a community meeting.

**Comment by jinchihe** [comment]
OK, will try to collect some requirements and discuss in community meeting. Thanks.

**Comment by gautamkmr** [comment]
Given that we want our users to select the cloud providers of their choice, we definitely need to add support for other cloud providers like AWS and Azure. We also need to make sure that fairing has feature parity among AWS, Azure and GCP.

**Comment by jinchihe** [comment]
@gautamkmr Fairing already supports AWS and Azure as backends. Thanks.
