### ISSUE TITLE
Fire off K8s job to train python models

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#47]
fairing should support firing off K8s jobs to train python models (e.g. xgboost/scikits) learn models.

Need to figure out
  1. What the syntax is
  1. How to move data back and forth

**Comment by ashahab** [comment]
Users are bringing data to notebook. Can the same work for job?

**Comment by wbuchwalter** [comment]
> If the notebook can pull in the data, why won't the job be able to do it also?

If the logic to access the data is in your code, then yes it will work out of the box.

However I suspect many users will want to access their data not through an API but instead rely on some pre-configured data store such as en EBS/AzureDisk or some already created PV. And we would need to find a way to allow users to specify these kind of sources without introducing too much complexity.

**Comment by ashahab** [comment]
I see. It's about allowing users input information that's not notebook
code, but related.

**Comment by jlewi** [comment]
@ashahab I think you are correct in that we want to use fairing to fire off scikit jobs as K8s jobs so they can run asynchronously on other nodes.

I think what @wbuchwalter is saying that we don't want to use fairing to move data around. To move data around we would use a shared filesystem that can be accessed by both the notebook and the K8s job. For this there are two possibilities

   1. An external shared filesystem that is directly accessed (e.g. object store like S3/HDFS/GCS)
   1. A PVC that can be mounted on the notebook pods and K8s Job

In either case its just about configuring the pods (notebook and K8s job) so that code can access the data.

To @wbuchwalter's point I think this where our discussion about using Admission Controllers could be useful. An administrator could configure one or more admission controllers so that appropriate volumes are mounted on pods to make data accessible. Or in the case of GCS/S3/HDFS the admission controller could ensure appropriate credentials are provided to each pod.

**Comment by zhenghuiwang** [comment]
The xgboost example for housing works right now after several issues being fixed. IIRC, Matt has been working on making it run in notebook @r2d4

**Comment by jlewi** [comment]
Will be fixed by #64

**Comment by r2d4** [comment]
Fixed by #64 

/close
