### ISSUE TITLE
Fairing supports local podman builder to submit jobs to CRI-O runtime

### ISSUE THREAD

**Issue by mochiliu3000** [kubeflow/fairing#472]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Environments like OCP 4 use CRI-O as default container runtime. In order to submit jobs to such environment, need to support podman builder to build and push images.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
It is better to also support image registry that built on CRI-O.

**Comment by jinchihe** [comment]
Great suggestion/feature, seems podman is being used for some user cases now... That's good to support that as a builder. Thanks @mochiliu3000

**Comment by mochiliu3000** [comment]
@googlebot I fixed it

**Comment by jlewi** [comment]
What is podman?

Would anything change if per kubeflow/fairing/issues/454 we switch to using Tekton to build docker images? i.e. is podman just a builder like Kaniko? So would it just be a matter of people defining Tekton tasks to build their images using podman and then firing them off with fairing?

**Comment by jinchihe** [comment]
@jlewi Podman is a daemonless container engine for developing, managing, and running OCI Containers on your Linux System. Containers can either be run as root or in rootless mode. 

Yes, I will take a high priority to take a look the Tekton with Fairing. For now I think it's better to support that as someone is going to use Fairing and may need to build image via podman. I noticed @mochiliu3000 has created a PR to implement that. Thanks.

**Comment by nrchakradhar** [comment]
If I am not mistaken, buildah is used for building container images. This has one advantage of being rootless compared to docker.
It would be better to offer all options for container builds: docker, kaniko, buildah/podman, tekton.
For tekton usage, additional setup may be needed which may not always be the case.

**Comment by mochiliu3000** [comment]
Hi @jlewi, Podman is a tool we use to build, maintain image and runtime on OpenShift. As OpenShift 4.X now use CRI-O as default container runtime, Podman is a suggested tool to replace docker. My team are now moving our existing model training workloads to OpenShift, so hope that fairing can better support such environment and scenario.

For details, see:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/managing_containers/index#using_podman_to_work_with_containers

**Comment by nrchakradhar** [comment]
> If I am not mistaken, buildah is used for building container images. This has one advantage of being rootless compared to docker.
> It would be better to offer all options for container builds: docker, kaniko, buildah/podman, tekton.
> For tekton usage, additional setup may be needed which may not always be the case.

In case somebody comes here for additional information about differences between podman and buildah, here are couple of links:
https://podman.io/blogs/2018/10/31/podman-buildah-relationship.html
https://developers.redhat.com/blog/2019/02/21/podman-and-buildah-for-docker-users/
