### ISSUE TITLE
Cannot do "import kubeflow.tfjob"

### ISSUE THREAD

**Issue by sakaia** [kubeflow/fairing#480]
/kind bug

**What steps did you take and what happened:**
`import kubeflow.tfjob` does not work.

instruction (following commands work successfully)
```
pip3 install kubeflow
python3
import kubeflow
import kubeflow.fairing
```

But following command fails with `ModuleNotFoundError: No module named kubeflow.tfjob`

```
import kubeflow.tfjob
```
**What did you expect to happen:**
`import kubeflow.tfjob` works fine

**Anything else you would like to add:**

Following command also does not work

import kubeflow.pipelines
import kubeflow.k8s

**Environment:**

- Fairing version: 0.0.3  but kubeflow.fairing.__version__ does not work
- Kubeflow version: 1.0
- Minikube version: I use microk8s
- Kubernetes version: (use `kubectl version`):1.18.0
- OS (e.g. from `/etc/os-release`): Ubuntu 19.10

**Comment by jinchihe** [comment]
You should install `kubeflow-fairing` 
```
pip3 install kubeflow-fairing
```
