### ISSUE TITLE
No module named 'fairing.training

### ISSUE THREAD

**Issue by hamedhsn** [kubeflow/fairing#49]
getting this when trigger a job
'Traceback (most recent call last):'
'  File "/app/main.py", line 31, in <module>'
'    from fairing.training import kubeflow'
"ModuleNotFoundError: No module named 'fairing.training'"

Seems like you have not published the new version.  `fairing==0.0.3`

**Comment by hamedhsn** [comment]
@wbuchwalter can you have a look at this?

**Comment by jlewi** [comment]
@hamedhsn Might be helpful if you could provide a little more context about what you ran to get that error?

/cc @r2d4

**Comment by wbuchwalter** [comment]
@hamedhsn For now please do pip install from a commit id, we have to release a new version as you said.

**Comment by hamedhsn** [comment]
was just testing the provided example and ran into the issue.

**Comment by suensummit** [comment]
I installed `fairing` using a commit id but still ran into this issue:
```
!pipenv install git+git://github.com/kubeflow/fairing.git@132f99d75bcd8dd8377e87aed5d317eede5aa6a0#egg=fairing
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-30-6f92c961e2d7> in <module>
----> 1 fairing.config.set_model(SimpleModel())

AttributeError: module 'fairing' has no attribute 'config'
```

**Comment by suensummit** [comment]
Oh it seems something not finished yet...
https://github.com/kubeflow/fairing/pull/68/files#r258633717

> I installed `fairing` using a commit id but still ran into this issue:
> 
> ```
> !pipenv install git+git://github.com/kubeflow/fairing.git@132f99d75bcd8dd8377e87aed5d317eede5aa6a0#egg=fairing
> ```
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-30-6f92c961e2d7> in <module>
> ----> 1 fairing.config.set_model(SimpleModel())
> 
> AttributeError: module 'fairing' has no attribute 'config'
> ```

**Comment by karthikv2k** [comment]
closing this as the API mentioned here is changed. Please reopen if you encounter this on current master.
