### ISSUE TITLE
Fairing Serving job user can not set the custom environment vars

### ISSUE THREAD

**Issue by songm28** [kubeflow/fairing#492]
/kind feature

**Describe the solution you'd like**
so far, for the Faring Serving Job , user can not set the specific custom environment vars like the custom command, is it possible let user to set the env parmameters like command in the preprocessor to build in the pod spec?

_[class BasePreProcessor(object)](https://github.com/kubeflow/fairing/blob/master/kubeflow/fairing/preprocessors/base.py):
    """Prepares a context that gets sent to the builder for the docker build and sets the entrypoint
    :param input_files: the source files to be processed
    :param executable: the file to execute using command (e.g. main.py)
    :param output_map: a dict of files to be added without preprocessing
    :param path_prefix: the prefix of the path where the files will be added in the container
    :param command: the command to pass to the builder_

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jinchihe** [comment]
@songm28 Are you interested implementing this? Thanks.

**Comment by songm28** [comment]
@jinchihe ok, I will make the change.

**Comment by jinchihe** [comment]
@songm28 I already implement that in #515, would you please help to review? Thanks a lot!
