### ISSUE TITLE
Requirements.txt missing from pip package

### ISSUE THREAD

**Issue by bomerzz** [kubeflow/fairing#496]
/kind bug

pip install kubeflow-fairing
Collecting kubeflow-fairing
Downloading https://files.pythonhosted.org/packages/ab/7a/45aa727f59386aa0bccd1314c4c3837352eb04c43836c25871fbc372abca/kubeflow-fairing-0.7.2.tar.gz (98kB)
100% |████████████████████████████████| 102kB 913kB/s
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-build-HVs6FX/kubeflow-fairing/setup.py", line 3, in
with open('requirements.txt') as f:
IOError: [Errno 2] No such file or directory: 'requirements.txt'

----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HVs6FX/kubeflow-fairing/

Within the tar.gz the requirements.txt is missing and not packaged together for the pip release.

**Comment by jinchihe** [comment]
/assign

I going to add that.

**Comment by jinchihe** [comment]
@bomerzz which version you used? I tried that, the package can be installed.

```
(python36) [root@jinchi1 ~]# pip install kubeflow-fairing
Collecting kubeflow-fairing
  Downloading kubeflow_fairing-0.7.3-py3-none-any.whl (161 kB)
     |################################| 161 kB 824 kB/s
Requirement already satisfied: google-cloud-storage>=1.13.2 in /opt/python/python36/lib/python3.6/site-packages (from kubeflow-fairing) (1.26.0)

.....

Requirement already satisfied: pycparser in /opt/python/python36/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.1.0->adal>=1.2.2->kfserving>=0.2.1.1->kubeflow-fairing) (2.19)
Installing collected packages: kubeflow-fairing
Successfully installed kubeflow-fairing-0.7.3
```

But yeah, we should add the requirements.txt, so that user can download tar source code from Pypi.

**Comment by bomerzz** [comment]
At the time of posting this issue, I was using version 0.7.2
