### ISSUE TITLE
Would you describe the version relation ship between github code and pypi?

### ISSUE THREAD

**Issue by sakaia** [kubeflow/fairing#499]
/kind bug

**What steps did you take and what happened:**
Would you describe the version relation ship between github code and pypi?
For Pypi, currenly version is 0.7.2. But github does not have such version 

- [(github)fairing](https://github.com/kubeflow/fairing/releases)
- [(pypi) kubeflow-fairing](https://pypi.org/project/kubeflow-fairing/#history)

**What did you expect to happen:**
The version relationship is consistent with github and pypi

**Anything else you would like to add:**
Nothing

**Environment:**
This is github and pypi  issue. I skip this

- Fairing version: (use `python -c "import kubeflow.fairing; print(kubeflow.fairing.__version__)"`):
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**NOTE**: If you are using fair from master, please provide us the git commit hash.

**Comment by jinchihe** [comment]
we added 0.7.3 release (tag) which is match with kubeflow-fairing 0.7.3 release. Will add tag in future major release. Thanks.
