### ISSUE TITLE
Release Kubeflow Fairing 1.0

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/fairing#503]
We are going to release new stable Kubeflow Fairing 1.0 release, with some feature enhancement and bug fix. we need to go though the recent issue and pick P1/S1 issues and fix that before release. Thanks.

/cc @jlewi

**Comment by jinchihe** [comment]
The version will be released with Kubeflow 1.1, as planed in https://github.com/kubeflow/kubeflow/issues/5022

**Comment by jinchihe** [comment]
kubeflow-fairing v1.0.0 released: https://pypi.org/project/kubeflow-fairing/

**Comment by jlewi** [comment]
Woo Hoo great work @jinchihe
