### ISSUE TITLE
Fairing nslookup increase retries

### ISSUE THREAD

**Issue by aakarshg** [kubeflow/fairing#529]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Currently we default to [600 retries for nslookup ](https://github.com/kubeflow/fairing/blob/master/kubeflow/fairing/frameworks/utils.py#L48), and its hardcoded, ideally this should be either a parameter that we can pass to the lightgbm.execute() or another param from the config dictionary potentially. The 600 seconds might seem enough, but in reality there's cases where it takes > 10 minutes, and then the whole run just fails. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by aakarshg** [comment]
@jlewi do you think this can be done for a 1.0.2 release? I can try to help :)

**Comment by jinchihe** [comment]
@aakarshg Thanks. That's great if you can work on this. welcome your PRs, we can get the enhancement before next release.

**Comment by jlewi** [comment]
https://github.com/kubeflow/fairing/blob/53acc7fe2e0d91cf2c7165828099fe59c4028186/kubeflow/fairing/frameworks/utils.py#L48
I would suggest using  https://pypi.org/project/retrying/ with exponential backoff and setting the max time to wait.

@aakarshg fairing releases are up to @jinchihe

**Comment by aakarshg** [comment]
@jinchihe the PR has been merged, do you think we can do a 1.0.2 release ? If there's anything else that I can help with too lmk :)

**Comment by jinchihe** [comment]
@aakarshg Just released kubeflow-fairing v1.0.2 https://pypi.org/project/kubeflow-fairing/  Thanks.
