### ISSUE TITLE
Cluster builder does not set Dockerfile command

### ISSUE THREAD

**Issue by dippynark** [kubeflow/fairing#538]
/kind bug

**What steps did you take and what happened:**

When using the cluster builder (kaniko) Fairing does not set the command in the Dockerfile.

This is handled correctly when using the docker builder ([here](https://github.com/kubeflow/fairing/blob/fddd3983f7ae4fd44017308eeded2fcdb9ed29fd/kubeflow/fairing/builders/docker/docker.py#L49)) but with the cluster builder this passthrough of the command from the preprocessor is not performed ([here](https://github.com/kubeflow/fairing/blob/fddd3983f7ae4fd44017308eeded2fcdb9ed29fd/kubeflow/fairing/builders/cluster/cluster.py#L51-L55)).

In particular this prevents the function preprocessor's command from running by default when the container is started ([here](https://github.com/kubeflow/fairing/blob/fddd3983f7ae4fd44017308eeded2fcdb9ed29fd/kubeflow/fairing/preprocessors/function.py#L93-L95))

**What did you expect to happen:**

I'd expect the Dockerfile command to be set and in general for the cluster builder's Dockerfile to be the same as the docker builder's Dockerfile so that the two builders are consistent.

**Environment:**

- Fairing version: 1.0.2
- Kubeflow version: v1beta1
- Kubernetes version: v1.17.9-gke.1503
- OS (e.g. from `/etc/os-release`): Container-Optimized OS from Google

**Comment by Minkyu-Choi** [comment]
If you use fairing.config.run method with both builder and deployer specified, then deployer get it's pod spec from builder's generate_pod_spec method.
And as you can [here](https://github.com/kubeflow/fairing/blob/9ca6a1138529b3f0b21979d62c7cb1f303bc52e0/kubeflow/fairing/builders/base_builder.py#L48), deployer's container command is set by preprocessor's command at runtime.

But, there's no explicit CMD specified in container image. So, this can be a problem for other use case like pipeline. I'll going to submit PR fixing this.
