### ISSUE TITLE
Serving with seldom failing

### ISSUE THREAD

**Issue by midhun1998** [kubeflow/fairing#547]
/kind bug /kind question

- Edited and used [XGBoost ](https://github.com/kubeflow/fairing/blob/master/examples/prediction/xgboost-gkeop.ipynb)example to try fairing in Kubeflow in EKS.
- `ClusterBuilder.build()` was successfully building the image and pushing to ECR.
- Serving deployer was used to deploy an endpoint.
- The pod was deployed with Seldon running inside.
- The pod crashed with an error.(Attaching a screenshot)
![IMG_20201210_145935_LL.jpg](https://user-images.githubusercontent.com/24776450/101754486-cddccf00-3af9-11eb-81da-9d6eff974fef.jpg)

**What did you expect to happen:**
- Expected Seldon to deploy and run with `REST `argument.

**Anything else you would like to add:**
I have a doubt if Seldon 1.5.0 still supports the `REST `argument. Also when I ran a pod with a similar deployment spec but without REST argument the pod was running fine.

**Environment:**

- Fairing version: 1.0.1
- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1beta1
- Kubernetes version: (use `kubectl version`): 1.17

**Comment by jinchihe** [comment]
Yeah, we may need to upgrade that.

**Comment by midhun1998** [comment]
Hi @jinchihe . Thanks for confirming. If only the `REST` argument has to be removed from [here ](https://github.com/kubeflow/fairing/blob/e62a6c818b15496a06823c419850db2904b450a6/kubeflow/fairing/deployers/serving/serving.py#L47) I can create a PR because I'm just getting started with Kubeflow and seems like a good first issue. If I'm wrong please do guide me.  

P.S: I just realized it is not right to remove that argument as it may disrupt backward compatibility. If you feel it's a good first issue do provide some guidance. Thanks. 😄

**Comment by jinchihe** [comment]
Yeah, That's great if you can create a PR with your investigation. Thanks!
