### ISSUE TITLE
Remove Metaparticle

### ISSUE THREAD

**Issue by wbuchwalter** [kubeflow/fairing#8]
Metaparticle isn't maintained anymore, so we probably should just used the kubernetes client directly instead.

**Comment by hamedhsn** [comment]
@wbuchwalter happy to work on this. when do you think you will merge the configmap PR https://github.com/kubeflow/fairing/pull/15, we can reuse the KubeClient part.

**Comment by AdrianLsk** [comment]
You can use s2i as a replacement for metaparticle https://blog.openshift.com/create-s2i-builder-image/
